version: '3'
services:
  headscale:
    image: 'headscale/headscale:latest'
    ports:
      - '10.10.10.10:8080:8080'
      - '10.10.10.10:9090:9090'
    volumes:
      - /home/anurag/docker/sanog39-demo.anuragbhatia.com/headscale:/etc/headscale
    restart: unless-stopped
    command: headscale serve

  caddy:
    image: 'caddy:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /home/anurag/docker/sanog39-demo.anuragbhatia.com/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config


volumes: 
  caddy_data:
  caddy_config: 